use_frameworks!

platform :ios, '14.0'

install! 'cocoapods', :deterministic_uuids => false

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
  end
 end
end

target 'iosApp' do
    pod 'Reachability'
    pod 'shared', :path => '../shared/'
end