package com.presta.customer.network.longTermLoans.tst

data class TestModel(
    val availableAmount: Int,
    val committedAmount: Int,
    val created: String,
    val createdBy: String,
    val details: Details,
    val email: String,
    val firstName: String,
    val fullName: String,
    val hasFavoriteGuarantors: Boolean,
    val id: Int,
    val idNumber: String,
    val isEmailValidated: Boolean,
    val isTermsAccepted: Boolean,
    val lastName: String,
    val loanCount: Int,
    val memberGuaranteedLoans: List<MemberGuaranteedLoan>,
    val memberLoans: List<MemberLoan>,
    val memberNumber: String,
    val memberStatus: String,
    val phoneNumber: String,
    val pinSecret: String,
    val refId: String,
    val totalDeposits: Int,
    val totalShares: Int,
    val updated: String,
    val updatedBy: String
)